---
title: "Premier League Table Points Vs. Position Viz"
author: "Henry Poole"
date: "12/22/2018"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(tidyverse)
```

Read tables

```{r}
tableFiles <- list.files(path = "./tables", full.names = TRUE)
seasonTables <- lapply(tableFiles, function(x) {
  read_csv(x) %>% mutate(Squad = paste(substr(x, 14, 18), Squad, sep = " "))
})

allTables <- bind_rows(seasonTables) %>% mutate(Rank = factor(Rank))
```

Max/Min Points By Each Final Table Position (for labels in plot)

```{r}
maxPointsLabels <- allTables %>% group_by(Rank) %>% arrange(desc(Points), .by_group = TRUE) %>% top_n(n = 1, wt = Points) %>% filter(n() == 1)
minPointsLabels <- allTables %>% group_by(Rank) %>% arrange(desc(Points), .by_group = TRUE) %>% top_n(n = -1, wt = Points) %>% filter(n() == 1)
```


Dot + Box Plot Points vs Final Table Position

```{r}
theme_set(theme_bw())
g <- ggplot(data = allTables, mapping = aes(x = Rank, y = Points)) + 
  geom_boxplot() +
  geom_dotplot(binaxis = 'y',
               stackdir = 'center',
               dotsize = 1,
               binwidth = 1,
               stackratio = 1,
               fill = "blue") +
  geom_text(data = maxPointsLabels, mapping = aes(label = Squad), size = 2.25, vjust = -2) +
  geom_text(data = minPointsLabels, mapping = aes(label = Squad), size = 2.25, vjust = 2.5) +
  scale_y_continuous(breaks = seq(0, 100, 10), minor_breaks = seq(0, 100, 2)) + 
  labs(title = "Premier League Historical Results",
       subtitle = "Points vs. Final Table Position: 95-96 Through 17-18 Seasons",
       caption = "Source: fbref.com",
       x = "Final Table Position",
       y = "Points")

aspectRatio <- 2
ggsave(plot = g, height = 10, width = 10 * aspectRatio, device = "png", filename = "Premier_League_Table_Points_Vs_Position.png", path = "plots")
```

Max/Min Differential By Each Final Table Position (for labels in plot)

```{r}
maxDiffLabels <- allTables %>% group_by(Rank) %>% arrange(desc(GDiff), .by_group = TRUE) %>% top_n(n = 1, wt = GDiff) %>% filter(n() == 1)
minDiffLabels <- allTables %>% group_by(Rank) %>% arrange(desc(GDiff), .by_group = TRUE) %>% top_n(n = -1, wt = GDiff) %>% filter(n() == 1)
```

Dot + Box Plot Goal Differential vs Final Table Position
```{r}
theme_set(theme_bw())
g <- ggplot(data = allTables, mapping = aes(x = Rank, y = GDiff)) + 
  geom_boxplot() +
  geom_dotplot(binaxis = 'y',
               stackdir = 'center',
               dotsize = 1,
               binwidth = 1,
               stackratio = 1,
               fill = "blue") +
  geom_text(data = maxDiffLabels, mapping = aes(label = Squad), size = 2.25, vjust = -2) +
  geom_text(data = minDiffLabels, mapping = aes(label = Squad), size = 2.25, vjust = 2.5) +
  scale_y_continuous(breaks = seq(-80, 80, 10), minor_breaks = seq(-80, 80, 2)) + 
  labs(title = "Premier League Historical Results",
       subtitle = "Goal Differential vs. Final Table Position: 95-96 Through 17-18 Seasons",
       caption = "Source: fbref.com",
       x = "Final Table Position",
       y = "Goal Differential")

aspectRatio <- 2
ggsave(plot = g, height = 10, width = 10 * aspectRatio, device = "png", filename = "Premier_League_Table_Differential_Vs_Position.png", path = "plots")
```

